parameters.solvers_invoke = ["gsds", "lincoa"];
parameters.problems_mindim = 1;
parameters.problems_maxdim = 5;
parameters.is_noisy = true;
parameters.noise_level = 1e-4;
parameters.num_random = 5;
parameters.parallel = true;
parameters.version = "now";
parameters.fmin_type = "real-randomized";
profile_bds(parameters);